import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="max-w-4xl mx-auto p-10 md:p-20 font-sans text-gray-800 leading-relaxed">
      <Link href="/" className="text-blue-600 hover:underline mb-8 block">← Back to Home</Link>
      
      <h1 className="text-4xl font-black mb-4">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-10">Effective Date: April 27, 2026</p>

      <section className="space-y-8">
        <div>
          <h2 className="text-xl font-bold italic text-blue-600">Please read these terms carefully before using our service.</h2>
        </div>

        <div>
          <h2 className="text-xl font-bold">1. Acceptance of Terms</h2>
          <p>By accessing **Shopify Compliance Agent**, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.</p>
        </div>

        <div>
          <h2 className="text-xl font-bold">2. Description of Service</h2>
          <p>We provide an AI-driven auditing tool designed to help Shopify merchants identify potential regulatory gaps. Our service is a **one-time audit** generated based on your store  public data at the time of the request.</p>
        </div>

        <div className="bg-yellow-50 p-6 border-l-4 border-yellow-400 rounded-r-lg">
          <h2 className="text-xl font-bold text-yellow-800 underline">3. AI Accuracy Disclaimer (Important)</h2>
          <p className="mt-2 text-yellow-900">Our audits are generated by Artificial Intelligence. While we strive for high accuracy, AI can occasionally produce errors or &quot;hallucinations.&quot; 
            <strong> This report does not constitute legal advice.</strong> You should consult with a qualified legal professional for final compliance verification.
          </p>
        </div>

        <div>
          <h2 className="text-xl font-bold">4. Payments and Refunds</h2>
          <ul className="list-disc ml-5 mt-2 space-y-2">
            <li><strong>Pricing:</strong> All services are charged as a one-time fee of ₹49.</li>
            <li><strong>Payment:</strong> Payments are processed securely via <strong>Razorpay</strong>.</li>
            <li><strong>Refunds:</strong> Due to the digital nature of the instant audit, we do not offer refunds once the analysis has been generated and delivered.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-xl font-bold">5. Limitations of Liability</h2>
          <p>Shopify Compliance Agent and its developers shall not be held liable for any legal fines, loss of revenue, or business interruptions resulting from the use or misuse of our AI-generated reports.</p>
        </div>

        <div>
          <h2 className="text-xl font-bold">6. Governing Law</h2>
          <p>These terms are governed by the laws of India. Any disputes arising from the use of this service shall be subject to the exclusive jurisdiction of the courts in your city/state.</p>
        </div>
      </section>

      <footer className="mt-20 pt-10 border-t border-gray-100 text-center text-gray-400 text-sm">
        &copy; 2026 Shopify Compliance Agent. All rights reserved.
      </footer>
    </div>
  );
}